server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/gymhubdb
    username: gymhub
    password: gymhub

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "my-super-secret-jwt-key-which-is-long-enough-123456"
  expiration: 86400000

